fconc: fconc.o dowrite.o write_file.o 
  gcc -Wall fconc.o dowrite.o write_file.o -o fconc

fconc.o: fconc.c
  gcc -Wall -c fconc.c
    
dowrite.o: dowrite.c
  gcc -Wall -c dowrite.c
      
write_file.o: write_file.c
  gcc -Wall -c write_file.c
